### ISSUE TITLE
Objective C version of CryptoExport Manager

### ISSUE THREAD

**Issue by Surezt22** [DigitalLeaves/CryptoExportImportManager#1]
I would like to have the objective C version of the CryptoExportManager.

**Comment by DigitalLeaves** [comment]
Sorry,that's not gonna happen unless you code it yourself. Objective-C code is technical debt right now.

**Comment by mdejongappthority** [comment]
Forked an Objective-C port here: https://github.com/mdejong/CryptoExportImportManager.git
