### ISSUE TITLE
Load EC Public key from importPublicKeyReferenceFromDERCertificate

### ISSUE THREAD

**Issue by deepesh-vasthimal-cko** [DigitalLeaves/CryptoExportImportManager#13]
Does importPublicKeyReferenceFromDERCertificate method support certificate which are of type EC ?. When I pass in a cert which is of EC type it returns nil. Can you please help.

**Comment by DigitalLeaves** [comment]
Sorry, I am not maintaining this software anymore. Thanks anyway for asking, and hope you can come up with a solution.
