### ISSUE TITLE
Crashed on bin code when calling exportPublicKeyToPEM

### ISSUE THREAD

**Issue by whiteholekong** [DigitalLeaves/CryptoExportImportManager#14]
I used this library for months, it works very fine. Thank you very much. 
But after updated the latest Xcode Version 11.4 (11E146), the deployment crash when calling exportPublicKeyToPEM. The library also work fine on development. 

Please help!

Crashed: com.apple.main-thread
EXC_BREAKPOINT 0x0000000183d1be50

0	libsystem_malloc.dylib	nanov2_allocate_from_block$VARIANT$mp.cold.1 + 36
1	libsystem_malloc.dylib	nanov2_find_block_and_allocate$VARIANT$mp + 514
2	libsystem_malloc.dylib	nanov2_allocate$VARIANT$mp + 124
3	libsystem_malloc.dylib	nanov2_malloc$VARIANT$mp + 60
4	libsystem_malloc.dylib	malloc_zone_malloc + 156
5	libsystem_malloc.dylib	malloc + 28
6	libswiftFoundation.dylib	__DataStorage.init(length:) + 144
7	my app				<compiler-generated> - Line 4302677292
						specialized Data._Representation.init(count:) + 4302677292
8	my app				<compiler-generated> - Line 4300942760
						specialized CryptoExportImportManager.exportRSAPublicKeyToDER(_:keyType:keySize:) + 4300942760
9	my app				CryptoExportImportManager.swift - Line 144
						CryptoExportImportManager.exportPublicKeyToPEM(_:keyType:keySize:) + 144

**Comment by DigitalLeaves** [comment]
Sorry, I am not maintaining this software anymore. Hope you can find a solution.
