### ISSUE TITLE
Error in CryptoExportImportManager

### ISSUE THREAD

**Issue by donadley** [DigitalLeaves/CryptoExportImportManager#5]
I am getting a swift compilation error on the following line that I do not quite understand. Have you send this error before?

CryptoExportImportManager/CryptoLoadExternalCertificate/CryptoExportImportManager.swift:107:46: Cannot convert value of type 'UInt32' to specified type 'SecTrustResultType'

error line: var resultType: SecTrustResultType = UInt32(0) // result will be ignored.

I am using XCODE version 8.

**Comment by donadley** [comment]
For some reason the UInt32 would not unwrap to SecTructResultType. I would love to understand why this is an issue but until then I changed the line to the following.
var resultType: SecTrustResultType = SecTrustResultType(rawValue: 0)! // result will be ignored.

**Comment by DigitalLeaves** [comment]
The code was not yet ported to Swift 3 / XCode 8. Should be working now.
