### ISSUE TITLE
How to export a RSA private key (2048)

### ISSUE THREAD

**Issue by Shafi2017** [DigitalLeaves/CryptoExportImportManager#7]
After spending nearly 4 days astray with no luck, I used your lib and its fantastic in one go on our PHP server. However I now want to export private key same way so that it can be used for decrypt back in our iOS app.
Will be very thankful for quick reply. Your help can resolve blocker issue in project!

Thanks
Shafi

**Comment by DigitalLeaves** [comment]
Hi there Shafi,

Thanks, I'm glad it was useful to you. The only way is by means of a full certificate. There's no way you can import just a key in iOS. I wrote a full blog post about that. You can find it here:

https://digitalleaves.com/blog/2015/10/sharing-public-keys-between-ios-and-the-rest-of-the-world/ <https://digitalleaves.com/blog/2015/10/sharing-public-keys-between-ios-and-the-rest-of-the-world/>

Best regards.


             <https://digitalleaves.com/>          

Ignacio Nieto Carvajal  / senior freelance developer  
contact@digitalleaves.com <mailto:contact@digitalleaves.com>
Digital Leaves  
https://digitalleaves.com <https://digitalleaves.com/>
   <https://twitter.com/digitalleaves>     <https://www.facebook.com/DigitalLeaves/>     <https://es.linkedin.com/in/digitalleaves>     <https://github.com/DigitalLeaves>

**Comment by Shafi2017** [comment]
Thanks a lot for the quick help!
Basically I want to generate RSA keypair. Using your crypto manager I'm able to generate a public key that I send to my server. Its working perfectly right there. 
Our sever encrypts some message successfully there with the same public key and sends it to my iOS app. Now I want decrypt the message with my private key. But I don't have the private key.

However I see that crypto manager generates key pair, means private key as well. But the format of the key is not same as public key.
So how do we get the private key and in the same format as public key using the crypto manager?

Please help!
Thank you
Shafi

**Comment by h3smith** [comment]
You don't need direct access to the private key if it is stored in the keychain to decrypt. You should use the asymmetric key in the keychain to decrypt the symmetric key and use that symmetric key to decrypt your data.

**Comment by DigitalLeaves** [comment]
Hi Shafi!
The process is the following: you need to generate certificates for your server, extract their public/private key pairs, and then send the certificate of the server (with the public key) to the client, the client will use my software to communicate with the server. On the other hand, the client will generate a keypair (again, you can use my tool to do that) and export the public key, and send that to your server. The server can import it properly, and you have both communication channels covered.

**Comment by Shafi2017** [comment]
Thanks for the quick help!
What we are trying to do is :
1) generate key par in iOS device.
2) send this public key to server. PUB1
3) signed some string (a symmetric key) using this PRIVATE key. S1.
4) send signed string S1 (generated in step 3) to the server.
5) Using PUB1, server tries to check if S1 is signed properly.
Server guy is initially having problem is step 5 as its throwing exception that the public key PUB1 is not valid. But using your tool we successfully doing this. Public key is working server side perfectly.
Now problem is how to get the private key so that our client can sign (step 3)
Our Android app (the client) doesn’t have any issues and its working this way without any issue however we want to do the same with iOS app.
Is that possible?
Can we get a valid PRIVATE key in iOS like we are getting a PUBLIC key using your tool?
Thank you
Shafi

**Comment by DigitalLeaves** [comment]
We'll continue in the blog, Shafi :)

**Comment by Shafi2017** [comment]
Alright!
